id: I6C6D6DCF
ocr_import_info:
  timestamp: '2023-09-28T02:50:19.433594+00:00'
  batch_id: batch-1bf3
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: Dharma Kyab
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-09-28 03:25:46.428358+00:00
last_modified: 2023-09-28 03:25:46.428364+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W29100
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29100
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: དམ་པའི་ཆོས་མངོན་པ་མཛོད་ཀྱི་རྣམ་བཤད་བློ་གསལ་ཡིད་ཀྱི་མུན་སེལ་ཀུན་གསལ་ཉི་མ།
  languages:
  - bo
  author: འཛམ་ཐང་མཁན་པོ་ཚོགས་གཉིས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.8716065891128987
  ocr_word_median_confidence_index: 0.915109325
bases:
  I5113:
    source_metadata:
      id: http://purl.bdrc.io/resource/I5113
      total_pages: 122
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I5113.txt
    statistics:
      ocr_word_median_confidence_index: 0.915109325
      ocr_word_mean_confidence_index: 0.8716065891128987
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
